language: node_js

node_js:
  - 'node'
  - 'lts/*'
  - '12'
  - '11'
  - '10'

cache:
  directories:
    - 'node_modules'
  yarn: true

install:
  - yarn install

script:
  - yarn test
  - yarn build

branches:
  only:
    - master
