language: node_js

node_js:
  - 'node'
  - 'lts/*'
  - '12'
  - '11'
  - '10'

branches:
  only:
    - master

cache:
  directories:
    - 'node_modules'
  yarn: true

script:
  - yarn build
  - yarn test
