language: node_js

node_js:
  - 'node'
  - 'lts/*'
  - '11'
  - '10'

branches:
  only:
    - master

cache:
  directories:
    - 'node_modules'
  yarn: true

before_script:
  - yarn
  - yarn add -D coveralls

script:
  - yarn build
  - yarn test
  - yarn test --coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
